apiVersion: v1
kind: Service
metadata:
  name: azuresql
  namespace: infra
  labels:
    type: db
spec:
  ports:
    - port: 1433 # Port sur lequel le Service écoute
      targetPort: 1433 # Port sur lequel azuresql écoute
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: azuresql
  namespace: databases
subsets:
  - addresses:
      - ip: 192.168.1.165 # Adresse IP de votre base de données azuresql
    ports:
      - port: 1433 # Port sur lequel azuresql écoute
