apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Project for infra deployments like monitoring, databases, etc.
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/samymokhtari/samy.cloud.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
      name: in-cluster
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: muslimbot
  namespace: argocd
spec:
  description: Project for muslimbot namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/samymokhtari/samy.cloud.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "muslimbot"
      name: in-cluster
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: schnekzer
  namespace: argocd
spec:
  description: Project for schnekzer namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/samymokhtari/samy.cloud.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "schnekzer"
      name: in-cluster
