apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: muslimbot
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    debug

    [INPUT]
        Name              tail
        Path              /fluent-bit/logs/application.log
        Tag               kubernetes.muslimbot
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name            loki
        Match           kubernetes.*
        Host            loki.monitoring.svc.cluster.local
        Port            3100
        Labels          job=muslimbot
