---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gchr-secrets
  namespace: muslimbot
spec:
  encryptedData:
    .dockerconfigjson: AgBC+iq8jJGHMWYPO4Di3Wk4NJKMGA2CRmCEv6Efi375e8i0/sE8VHNucVqNvXzOemD8CvI8WmfPasWaIxEY2IWWZUDIb60tuV4DgNbVITRuDdKMvdP62NjkOqbFpYhiai441bws0W3+1DFqt1P4aeZbaOAMa7vD108OzFRCzcn9TUvHF1ys7Yodll8iC3Xzwsxqwxt9FxwRhcl80mcMsy7Pjji0U8ObGgN7MeYd2zqPxk9bSSjJecLUyz9Lnbk1IR0PnIodLY6MLwnommRXahu200ih990SZkPmIsHfFv2S1OiFcAvf4TpwUrrjboBK4O7jrbbYIB+hc+YIfMa93SQlh7/Dk6Eb2C0sU+4E16bpKyf+YWIwo0PfDP7C1i1DANNf7o4o9OWesF6kyrOIzOpPpt7498PvjUI/bgFIh7/5mnNOlJE3RftzxqiRy7jt36sZtb6JOVD8vYZFIvMb4T/h90+f2Kasha2lT5VABrOGfYEuGydu2yyFs57xjsFPgzfd7KK7K1tw+HA077vm3UgUyp65NuTmuCRaDF6ptroOjTO+KWw/pNyd0voWXyL4I6Xr2bM4nBp5UnlzCgmADD/HKJ+tEW0hAlPKdifNX9Krkxjjn/g0DAso8h8lP9itlDjm3MTANP/iiiE4uQq2FTo4+jOKmihj5x+wo9zf4GdcJj8W/W3bXj9qohdr2wlOXVr2wf2w9etyYGNtnpK+TlqZqc4xZch6y7Qp1z8HDdqMq8DxLzzLCNl69MtyczyJ7Fpd7NBXURCsMtm1OenhnP9E6u7eCE7zSvOXKLKgk1JGXxx6JoEe7XDLETp/C0SuX1Konrt7xvDzmVx1KPaHGVN7zeNnqesEYoQAYANbAwCa+n7dKZzoWwJYpGcE8M9jsylmiC5DhKcxzmOGxQwJJTB+XrCVLyVrZkk1msMyizxlY5sZ3h2CSe65+9EOu0ZKJi+I8y249jmtGu4tFTlJnWXYCqtpVcuf0i2kdawKstE=
  template:
    metadata:
      creationTimestamp: null
      name: gchr-secrets
      namespace: muslimbot
    type: kubernetes.io/dockerconfigjson
