apiVersion: v1
kind: Namespace
metadata:
  name: muslimbot
  labels:
    app: muslimbot
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: muslimbot-quota
  namespace: muslimbot
spec:
  hard:
    requests.cpu: "500m"
    limits.cpu: "650m"
    requests.memory: "2Gi"
    limits.memory: "2Gi"
