apiVersion: v1
kind: Namespace
metadata:
  name: muslimbot
  labels:
    app: muslimbot
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: muslimbot-quota
  namespace: muslimbot
spec:
  hard:
    requests.cpu: "60m"
    limits.cpu: "600m"
    requests.memory: "128Mi"
    limits.memory: "728Mi"
