apiVersion: v1
kind: PersistentVolume
metadata:
  name: muslimbot-pv
  labels:
    app: muslimbot
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/mnt/data/muslimbot"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muslimbot-pvc
  namespace: muslimbot
  labels:
    app: muslimbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
