---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secrets
  namespace: infra
spec:
  encryptedData:
    DB_PASS: AgASWDkNC8aDRo9hZPjmKVvxLPzPFGU8eBwfvct6z6nKfoUq2wye5+Vu3PrsLQVPW9iw3Ky5TCM7QlpjzoCWYiZSSbaZlyLAUxpBS2lAas4OZCmP+gf/0/r8QegNfND0/xlUlXbcQWfK9gMPyILVIcARi3zc/+fASQrMHf0nVZYEu2hz5VLJr1AOcbTW/Pajo3Q/KHIeSKvnjG915ydqAFkroRdBYYdNRDL3ZrQm+fzzH+Sstd0GSq4RfoYCZxV9WbfEu6fRhcPuqIJ+pp+Lw1lHZWpPF+GuHBIc6pT4tfsKU8xc4hZvaYy17oCzsZLV6Pgt9eB8HMMudh/Yv5p6sNpV6vrTFaln+nWhPiqE7y5IAODEnOmQQYDSuR764nwOZlfsEUYhw1Axqfi497Y4M1KuYTG55mU5ZZ5xafNw1ItSRWga3NrDe0mAl3P9ZUOQtbPAwCXkmFNb/pcthMUtNuF3tNd2KBqBmg0gXqi0CX3QJwS4yOyvxdphW6nA8pjOnhBw97XGTJX0Uf2goEpJK03s6hR27RiMwa5deB7WPsxVXVTm3vm6reDvcSivizn1v2Q5RAEDKQiN5Es5jlB3/uPA7ur8EfVMMMrApbn9e6y2E3vDIhfk++rzjXu7HsEAPknkJYqSoacxhsfiuITlfy6mB25OIMKg64aLRdnGKJjKH2xAox6qg07IARoOdQaWkZKda2/XmH3XjpGcx8vsAE5JZwuQwE0L5yJaXSiOUyGwBGgb7lM=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secrets
      namespace: infra
    type: Opaque
