---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secrets
  namespace: infra
spec:
  encryptedData:
    DB_PASS: AgBg3W/zR6xVBSuBp9DPe2X4i18fL5j3aETPHOHewfF6q3x0AqiTAzLjljqd7txVeuflsbVhVfl/ENscclTrq4O/5Q2bY/RPX6GmU5Xb9JLJDqIhLuU7KYXu7iNhR8Zirqq6ldJj5YCcMJ0cWHb6saRvJcQsFR032Ai/hCtYSiCtFBTVJ9JEaWigG0FkLQc/UZsuC11gIAoa844N3YlJFZHdHAU6dSBgJtkqHYTQs3VrY+PeoF9xCwacqcvOU8AF3+xm9v9lnUz6Bobfc9jBj5osKsBMzeZhk8Jj5rrtnNHJn1FqnYHkG/Z13ny5p8l8rs6qxluYFz5x3MoHlwRWm3rfceQUTY5O/JH53uFkV+YtoEMmhTv8e6h9KUTeGrZSddox8KR81mxmxDphCVs8G6c7J+TDKlwGqtj0dEDS9jKZonTphj9v0Uzarvuzmkwh+2x7BsVSulwfV/a0pM4As98oVY2pHt/kkbFHPpRt95HkuI5nTA+28t8/cD7xcY70dFiGGJYnLcbJONrWguwGdaQE0WCL5ofEBnhpumFmoRwPrcKN4vYcDDNIvVE6PvTRHAsbGr9CGQkvCUM2RYsnXJSjEKMGlOzoJ+83+OFu29Y/NANNJFMOj2H8eev6Nm5/XBfNWwR7u5bEIMZMV90NzMnfd6RyE8yRyq5MsSYH+cpp+QlhvXSHtAc2NV0CYLoeDWpLGr8/11SmuNhdvGP3vKz80W4Tv0dRObrhSSY=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secrets
      namespace: infra
    type: Opaque
