apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: infra
  labels:
    type: db
spec:
  ports:
    - port: 3306 # Port sur lequel le Service écoute
      targetPort: 3306 # Port sur lequel MariaDB écoute
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mariadb
  namespace: infra
subsets:
  - addresses:
      - ip: 192.168.1.165 # Adresse IP de votre base de données MariaDB
    ports:
      - port: 3306 # Port sur lequel MariaDB écoute
