name: Kubernetes manifests validation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: kubernetes/
          config_file: .yaml-lint.yaml

  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.4
        with:
          args: >
            -summary
            -strict
            -ignore-missing-schemas
            -kubernetes-version 1.29.0
            kubernetes/
